<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog\Catalog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings*.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
